wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1646892389
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 2
      - 15
      - 16
      4: 3.6.13
      5: 0.12.10
      8:
      - 5
data:
  desc: null
  value:
    datapath: /groups/tensorlab/rgundaka/code/data/piececonst_r421_N1024_smooth2.mat
    n_sample: 1
    name: Darcy
    nx: 421
    offset: 0
    sub: 7
    total_num: 1024
model:
  desc: null
  value:
    activation: gelu
    fc_dim: 128
    layers:
    - 64
    - 64
    - 64
    - 64
    - 64
    modes1:
    - 20
    - 20
    - 20
    - 20
    modes2:
    - 20
    - 20
    - 20
    - 20
    self_adaptive: true
others:
  desc: null
  value:
    entity: rishigundakaram
    group: darcy-finetune
    project: sa-pino
sa_lr:
  desc: null
  value: 1
self_adaptive:
  desc: null
  value: false
train:
  desc: null
  value:
    base_lr: 0.0025
    batchsize: 1
    ckpt: /groups/tensorlab/rgundaka/scripts/checkpoints/darcy-FDM/darcy-pino-nd.pt
    epochs: 500
    f_loss: 1.0
    milestones:
    - 100
    - 200
    - 300
    - 400
    sa_lr: 0.01
    save_dir: darcy-FDM-finetune
    save_name: darcy-finetune-pino.pt
    scheduler_gamma: 0.5
    xy_loss: 0.0
