data:
  name: 'Darcy'
  datapath: '/groups/tensorlab/rgundaka/code/data/piececonst_r421_N1024_smooth1.mat'
  total_num: 1024
  offset: 0
  n_sample: 1000
  nx: 421
  sub: 7

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [20, 20, 20, 20]
  modes2: [20, 20, 20, 20]
  fc_dim: 128
  activation: gelu
  self_adaptive: True

train:
  batchsize: 20
  epochs: 300
  milestones: [100, 150, 200]
  base_lr: 0.001
  sa_lr: 10
  scheduler_gamma: 0.5
  f_loss: 1.0
  xy_loss: 0.0
  save_dir: 'darcy-FDM'
  save_name: 'darcy-pino-sa-lr-100-nd.pt'

others:
  project: 'sa-pino'
  entity: 'rishigundakaram'
  group: 'darcy'


