wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1647156495
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      - 16
      4: 3.6.13
      5: 0.12.10
      8:
      - 5
data:
  desc: null
  value:
    Re: 500
    datapath: /groups/tensorlab/rgundaka/code/data/NS_data/NS_fine_Re500_T128_part2.npy
    n_sample: 100
    nt: 128
    nx: 128
    offset: 0
    shuffle: false
    sub: 1
    sub_t: 1
    time_interval: 1
    total_num: 100
model:
  desc: null
  value:
    fc_dim: 128
    layers:
    - 64
    - 64
    - 64
    - 64
    - 64
    modes1:
    - 8
    - 8
    - 8
    - 8
    modes2:
    - 8
    - 8
    - 8
    - 8
    modes3:
    - 8
    - 8
    - 8
    - 8
others:
  desc: null
  value:
    entity: rishigundakaram
    group: NS-test
    project: sa-pino
test:
  desc: null
  value:
    batchsize: 1
    ckpt: /groups/tensorlab/rgundaka/scripts/checkpoints/Re500-FDM/PINO-pretrain-Re500-1s-eqn256.pt
