data:
  Re: 500
  datapath: /groups/tensorlab/rgundaka/code/data/NS_data/NS_fine_Re500_T128_part2.npy
  n_sample: 1
  nt: 128
  nx: 128
  offset: 0
  shuffle: true
  sub: 2
  sub_t: 2
  time_interval: 1
  total_num: 100
model:
  fc_dim: 128
  layers:
  - 64
  - 64
  - 64
  - 64
  - 64
  modes1:
  - 8
  - 8
  - 8
  - 8
  modes2:
  - 8
  - 8
  - 8
  - 8
  modes3:
  - 8
  - 8
  - 8
  - 8
  self_adaptive: false
others:
  entity: rishigundakaram
  group: NS-finetune-LR-Search
  project: sa-pino
train:
  base_lr: 0.0025
  batchsize: 1
  ckpt: /groups/tensorlab/rgundaka/scripts/checkpoints/Re500-FDM/PINO-pretrain-Re500-1s-eqn256.pt
  epochs: 4000
  f_loss: 1.0
  ic_loss: 5.0
  milestones:
  - 500
  - 1500
  - 3000
  - 4000
  - 5000
  sa_lr: 0
  save_dir: Re500-FDM
  save_name: PINO-Re500-fintune-1s.pt
  scheduler_gamma: 0.5
  xy_loss: 0
