data:
  datapath: '/groups/tensorlab/rgundaka/code/data/NS_data/NS_fine_Re500_T128_part2.npy'
  Re: 500
  total_num: 100
  offset: 0
  n_sample: 1
  time_interval: 1
  nx: 128
  nt: 128
  sub: 2
  sub_t: 2
  shuffle: True

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128
  self_adaptive: False

train:
  batchsize: 1
  epochs: 4000
  milestones: [500, 1500, 3000, 4000, 5000]
  base_lr: 0.0025
  sa_lr: 0
  scheduler_gamma: 0.5
  ckpt: '/groups/tensorlab/rgundaka/scripts/checkpoints/Re500-FDM/PINO-pretrain-Re500-1s-eqn256.pt'
  ic_loss: 5.0
  f_loss: 1.0
  xy_loss: 0
  save_dir: 'Re500-FDM'
  save_name: 'PINO-Re500-fintune-1s.pt'

others: 
  project: 'sa-pino'
  group: 'NS-finetune-LR-Search'
  entity: 'rishigundakaram'




