data:
  datapath: '/groups/tensorlab/rgundaka/code/data/NS_data/NS_fine_Re500_T128_part0.npy'
  datapath2: '/groups/tensorlab/rgundaka/code/data/NS_data/NS_fine_Re500_T128_part1.npy'
  Re: 500
  total_num: 100
  offset: 0
  n_sample: 100
  time_interval: 1
  nx: 128
  nt: 128
  sub: 1
  sub_t: 1
  shuffle: True
  num_ics: 100000
  S2: 128
  T2: 128

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128

train:
  batchsize: 1
  data_iter: 0
  eqn_iter: 200
  epochs: 500
  milestones: [100, 200, 300, 400]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 5.0
  f_loss: 1.0
  xy_loss: 0.0
  save_dir: 'Re500-FDM'
  save_name: 'PINO-pretrain-Re500-1s-nd-100k-ics.pt'

others:
  project: 'sa-pino'
  entity: 'rishigundakaram'
  group: 'navier-stokes'
  tags: ['100k ics', '500 ep']


