wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1647155711
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      - 16
      4: 3.6.13
      5: 0.12.10
      8:
      - 5
data:
  desc: null
  value:
    datapath: /groups/tensorlab/rgundaka/code/data/piececonst_r421_N1024_smooth2.mat
    n_sample: 1000
    name: Darcy
    nx: 421
    offset: 0
    shuffle: false
    sub: 7
    total_num: 1024
model:
  desc: null
  value:
    activation: gelu
    fc_dim: 128
    layers:
    - 64
    - 64
    - 64
    - 64
    - 64
    modes1:
    - 20
    - 20
    - 20
    - 20
    modes2:
    - 20
    - 20
    - 20
    - 20
others:
  desc: null
  value:
    entity: rishigundakaram
    group: darcy-test
    project: sa-pino
test:
  desc: null
  value:
    batchsize: 1
    ckpt: /groups/tensorlab/rgundaka/scripts/checkpoints/darcy-FDM/darcy-pino-sa-lr-1-nd.pt
